// <auto-generated />
namespace RealEstateInvestment.MigrationsDb.dbContainer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterPercisionInPaymentMethodDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterPercisionInPaymentMethodDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081430402_AlterPercisionInPaymentMethodDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
