// <auto-generated />
namespace RealEstateInvestment.MigrationsDb.dbContainer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCHEQUEINBOXID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCHEQUEINBOXID));
        
        string IMigrationMetadata.Id
        {
            get { return "201909171551398_addCHEQUEINBOXID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
