// <auto-generated />
namespace RealEstateInvestment.MigrationsDb.dbContainer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddAccountsToProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAccountsToProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201907291206374_AddAccountsToProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
