// <auto-generated />
namespace RealEstateInvestment.MigrationsDb.dbContainer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADDJORNALFLAGINCONTRACTANDSTUTUSININSTALLMENT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDJORNALFLAGINCONTRACTANDSTUTUSININSTALLMENT));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290924319_ADDJORNALFLAGINCONTRACTANDSTUTUSININSTALLMENT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
